# Generated by Django 5.1.1 on 2024-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingnumber",
            name="customer_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="trackingnumber",
            name="destination_country_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="trackingnumber",
            name="origin_country_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="trackingnumber",
            name="weight",
            field=models.FloatField(),
        ),
    ]
